/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'littl' at '9/22/17 11:04 PM' with Gradle 2.14.1
 *
 * @author littl, @date 9/22/17 11:04 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
